In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

project_path = "/content/drive/MyDrive/Water_AI_Hackathon"
os.chdir(project_path)

print(os.getcwd())

/content/drive/MyDrive/Water_AI_Hackathon

In [4]:
import pandas as pd

df = pd.read_csv("datasets/scarcity.csv")

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df.head()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%),Water Scarcity Level
0,Argentina,2000,481.490000,235.431429,48.550000,20.844286,30.100000,1288.698571,3.255714,Moderate
1,Argentina,2001,455.063000,299.551000,48.465000,26.943000,22.550000,1371.729000,3.120000,Moderate
2,Argentina,2002,482.749231,340.124615,50.375385,29.042308,23.349231,1590.305385,2.733846,Moderate
3,Argentina,2003,452.660000,326.756667,49.086667,30.476000,24.440000,1816.012667,2.708000,Moderate
4,Argentina,2004,634.566000,230.346000,38.670000,36.670000,23.924000,815.998000,1.902000,Moderate

In [7]:
#process the dataset
processed_df = df.copy()

In [8]:
processed_df.dtypes

Country                                            object
Year                                                int64
Total Water Consumption (Billion Cubic Meters)    float64
Per Capita Water Use (Liters per Day)             float64
Agricultural Water Use (%)                        float64
Industrial Water Use (%)                          float64
Household Water Use (%)                           float64
Rainfall Impact (Annual Precipitation in mm)      float64
Groundwater Depletion Rate (%)                    float64
Water Scarcity Level                               object
dtype: object

In [9]:
#encode country and scarcity level
from sklearn.preprocessing import LabelEncoder

country_encoder = LabelEncoder()
processed_df["Country"] = country_encoder.fit_transform(processed_df["Country"])

scarcity_encoder = LabelEncoder()
processed_df["Water Scarcity Level"] = country_encoder.fit_transform(processed_df["Water Scarcity Level"])

In [18]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import joblib

df = pd.read_csv("datasets/scarcity.csv")  # adjust path if needed

scarcity_encoder = LabelEncoder()
scarcity_encoder.fit(df["Water Scarcity Level"])

joblib.dump(scarcity_encoder, "models/scarcity_encoder.pkl")

['models/scarcity_encoder.pkl']

In [19]:
country_encoder = LabelEncoder()
country_encoder.fit(df["Country"])

joblib.dump(country_encoder, "models/country_encoder.pkl")

['models/country_encoder.pkl']

In [10]:
processed_df.head()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%),Water Scarcity Level
0,0,2000,481.490000,235.431429,48.550000,20.844286,30.100000,1288.698571,3.255714,2
1,0,2001,455.063000,299.551000,48.465000,26.943000,22.550000,1371.729000,3.120000,2
2,0,2002,482.749231,340.124615,50.375385,29.042308,23.349231,1590.305385,2.733846,2
3,0,2003,452.660000,326.756667,49.086667,30.476000,24.440000,1816.012667,2.708000,2
4,0,2004,634.566000,230.346000,38.670000,36.670000,23.924000,815.998000,1.902000,2

In [11]:
#define features and target

X = processed_df.drop("Water Scarcity Level", axis=1)

y = processed_df["Water Scarcity Level"]

In [12]:
#train-test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
#feature scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [14]:
#create output folders

processed_df.to_csv(
    "/content/drive/MyDrive/Water_AI_Hackathon/outputs/processed_scarcity.csv",
    index=False
)

In [16]:
import joblib

joblib.dump(country_encoder, "country_encoder.pkl")
joblib.dump(scarcity_encoder, "scarcity_encoder.pkl")

['scarcity_encoder.pkl']

In [17]:
joblib.dump(
    country_encoder,
    "/content/drive/MyDrive/Water_AI_Hackathon/models/country_encoder.pkl"
)

joblib.dump(
    scarcity_encoder,
    "/content/drive/MyDrive/Water_AI_Hackathon/models/scarcity_encoder.pkl"
)

['/content/drive/MyDrive/Water_AI_Hackathon/models/scarcity_encoder.pkl']